# Generated by Django 5.0.1 on 2024-01-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_assessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.assessment'),
            preserve_default=False,
        ),
    ]
