# Generated by Django 5.0.1 on 2024-01-28 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_assessmentassign_assess_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assement_submitted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
