# Generated by Django 5.0.1 on 2024-01-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_submittedassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedassessment',
            old_name='assess',
            new_name='assess_id',
        ),
        migrations.RenameField(
            model_name='submittedassessment',
            old_name='user',
            new_name='user_id',
        ),
    ]
