# Generated by Django 5.0.1 on 2024-01-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_assess_submittedassessment_assess_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassessment',
            name='assess_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assement_submitted', to='authentication.assessment'),
        ),
    ]
