# Generated by Django 5.0.1 on 2024-01-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_question_created_by_alter_question_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.assessment'),
        ),
    ]
