# Generated by Django 5.0.1 on 2024-01-29 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_assessmentassign_assign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='assess_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.assessment'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
